@startuml

actor 事務職員
boundary 返却入力画面
boundary 返却確認画面
boundary 返却完了画面
control 返却完了画面を表示する
control 管理番号が入力されているか
control この項目を入力してくださいと表示する
control 管理番号が存在しているか
control 管理番号が間違っていますと管理番号の一覧を表示する
control 返却完了画面を表示する
control 返却された本が貸出予約されているか
control 貸出予約されていますと表示する
control 返却完了画面を表示する
entity 管理番号
entity 貸出情報

事務職員 ->返却入力画面:管理番号を入力し、次へを押す
事務職員 ->返却完了画面:決定ボタンを押す
返却入力画面 -> 管理番号が入力されているか:管理番号を確認
管理番号が存在しているか ->管理番号:GET()
管理番号-->管理番号が存在しているか:管理番号データ
返却完了画面 ->返却された本が貸出予約されているか
返却された本が貸出予約されているか <-- 貸出情報:GET()する
貸出予約されていますと表示する -> 返却完了画面:返却完了画面を表示する

alt 管理番号が入力されている
    返却入力画面 ->管理番号が存在しているか:管理番号が存在しているかに進む
else 管理番号が入力されていない
    返却入力画面 -> 返却入力画面 : 「この項目を入力してください」と表示する
end
alt 管理番号が存在する
    管理番号が存在しているか -> 返却確認画面
else 管理番号が存在しない
    管理番号が存在しているか-> 返却入力画面 : 「管理番号が間違っています」と管理番号の一覧を表示する
end
alt 返却された本が貸出予約されている
    返却確認画面 -> 返却完了画面 : 「～貸出予約されています～」と表示する
else 返却された本が貸出予約されていない
    返却確認画面->返却完了画面:返却完了画面を表示する
end
@enduml